src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TicketRepository::class)
 */
class Ticket
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $type_ticket;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_ticket;

    /**
     * @ORM\Column(type="text")
     */
    private $desc_ticket;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $status_ticket;

    /**
     * @ORM\ManyToOne(targetEntity=Clientes::class, inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $fkClient;

    /**
     * @ORM\OneToMany(targetEntity=Comentarios::class, mappedBy="fkTicket", cascade={"persist", "remove"})
     */
    private $comentarios;

    /**
     * @ORM\ManyToOne(targetEntity=Servicio::class, inversedBy="tickets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $service;




    public function __construct()
    {
        $this->comentarios = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTypeTicket(): ?string
    {
        return $this->type_ticket;
    }

    public function setTypeTicket(string $type_ticket): self
    {
        $this->type_ticket = $type_ticket;

        return $this;
    }

    public function getdateTicket(): ?\DateTimeInterface
    {
        return $this->date_ticket;
    }

    public function setdateTicket(\DateTimeInterface $date_ticket): self
    {
        $this->date_ticket = $date_ticket;

        return $this;
    }

    public function getDescTicket(): ?string
    {
        return $this->desc_ticket;
    }

    public function setDescTicket(string $desc_ticket): self
    {
        $this->desc_ticket = $desc_ticket;

        return $this;
    }

    public function getStatusTicket(): ?string
    {
        return $this->status_ticket;
    }

    public function setStatusTicket(string $status_ticket): self
    {
        $this->status_ticket = $status_ticket;

        return $this;
    }

    public function getFkClient(): ?Clientes
    {
        return $this->fkClient;
    }

    public function setFkClient(?Clientes $fkClient): self
    {
        $this->fkClient = $fkClient;

        return $this;
    }

    /**
     * @return Collection|Comentarios[]
     */
    public function getComentarios(): Collection
    {
        return $this->comentarios;
    }

    public function addComentario(Comentarios $comentario): self
    {
        if (!$this->comentarios->contains($comentario)) {
            $this->comentarios[] = $comentario;
            $comentario->setFkTicket($this);
        }

        return $this;
    }

    public function removeComentario(Comentarios $comentario): self
    {
        if ($this->comentarios->removeElement($comentario)) {
            // set the owning side to null (unless already changed)
            if ($comentario->getFkTicket() === $this) {
                $comentario->setFkTicket(null);
            }
        }

        return $this;
    }

    public function getService(): ?Servicio
    {
        return $this->service;
    }

    public function setService(?Servicio $service): self
    {
        $this->service = $service;

        return $this;
    }




}

src/Controller/TicketsController.php
<?php

namespace App\Controller;

use App\Entity\Clientes;
use App\Entity\Comentarios;
use App\Entity\Direccion;
use App\Entity\Servicio;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Filesystem\Exception\IOExceptionInterface;
use Symfony\Component\Filesystem\Filesystem;
use App\Entity\Ticket;
use App\Form\NewTicketType;
use Symfony\Component\HttpFoundation\Request;

class TicketsController extends AbstractController
{
    protected $em;

    /**
     * @var EntityManagerInterface
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->em = $entityManager;
    }

    /**
     * @Route("/tickets", name="tickets")
     */
    public function index(): Response
    {
        $tickets = $this->em
            ->getRepository(Ticket::class)
            ->findAll();
        $response = array();
        foreach ($tickets as $ticket) {
                $response[] = array(
                $ticket->getId(),
                $ticket->getTypeTicket(),
                $ticket->getDateTicket()->format('Y-m-d H:i:s'),
                $ticket->getDescTicket(),
                $ticket->getStatusTicket(),
            );
        }
        return $this->render('tickets/index.html.twig', [
            'response' => json_encode($response)
        ]);
    }

    /**
     * @Route("/tickets/selector", name="selectorTickets")
     */
    public function clientSelector()
    {
        $response = array();
        foreach (($this->getDoctrine()
            ->getRepository(Clientes::class)
            ->findAll()) as $cliente) {
            $response[] = array(
                $cliente->getId(),
                $cliente->getNameClient(),
                $cliente->getEmailClient(),
                $cliente->getPhoneClient(),
            );
        }
        return new JsonResponse([
            'status' => true,
            'msg' => $this->renderView('tickets/clientSelector.html.twig', [
                'response' => json_encode($response),
            ])
        ]);
    }

    /**
     * @Route("/tickets/create/{id}", name="createTickets")
     */
    public function create($id): Response
    {
        $cliente = $this->em->getRepository(Clientes::class)->findOneBy([
            'id' => $id
        ]);
        $response = array();
        foreach (($this->em->getRepository(Servicio::class)->findAllServicesCliente($id)) as $s) {
            $response[] = array(
                $s->getId(),
                $s->getFkAddress()->getNameAddress(),
                $s->getIpService(),
            );
        }
        return $this->render('tickets/create.html.twig', [
            'id' => $id,
            'name' => $cliente->getNameClient(),
            'response' => json_encode($response),
        ]);
    }

    /**
     * @Route("/tickets/create/{id}/{service}", name="createTicketsNext")
     */
    public function createNext($id, $service, Request $request): Response
    {
        $form = $this->createForm(NewTicketType::class, new Ticket());
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $type = $form['type_ticket']->getData();
            $status = $form['status_ticket']->getData();
            $desc = $form['desc_ticket']->getData();
            $flag = true;
            $msg = "";
            if ($type == null || $status == null || $desc == null) {
                $flag = false;
                $msg = "Algun dato esta vacio";
            }
            if ($flag) {
                $ticket = new Ticket();
                $ticket->setDescTicket($desc);
                $ticket->setTypeTicket($type);
                $ticket->setStatusTicket($status);
                $ticket->setFkClient($this->em->getRepository(Clientes::class)->findOneBy(['id' => $id]));
                $ticket->setService($this->em->getRepository(Servicio::class)->findOneBy(['id' => $service]));
                $ticket->setdateTicket(new \DateTime());
                $this->em->persist($ticket);
                try {
                    $this->em->flush();
                    $msg = "Se ha insertado correctamente";
                } catch (\Exception $e) {
                    $flag = false;
                    $msg = $e->getMessage();
                }
            }
            return new JsonResponse([
                'status' => $flag,
                'msg' => $msg,
            ]);
        }
        return $this->render('tickets/createWithService.html.twig', [
            'form' => $form->createView()
        ]);
    }

    /**
     *
     * @Route("/tickets/fetchAddress/{id}", name="fetchAddress")
     */
    public function createFetchAddress($id)
    {
        $response = array();
        foreach (($this->em
            ->getRepository(Direccion::class)
            ->findBy([
                'clientes' => $id
            ])) as $a) {
            $response[] = array(
                'id' => $a->getId(),
                'address' => $a->getNameAddress()
            );
        }
        return $this->json([
                'address' => $response
            ]
        );
    }

    /**
     * @Route("/tickets/show/{id}", name="showTickets")
     */
    public function show($id)
    {
        $tickets = $this->em
            ->getRepository(Ticket::class)
            ->findOneBy([
                'id' => $id
            ]);
        $response = array();
        foreach ($tickets->getComentarios() as $c) {
            $response[] = array(
                'comment' => $this->renderView('tickets/coments/comment.html.twig', [
                    'i' => $c->getId(),
                    'c' => $c->getCommentComment(),
                    'st' => $c->getImageComment(),
                    'file' => $c->getFilename(),
                ]),

            );
        }
        return $this->render('tickets/show.html.twig', [
            'ticket' => $tickets,
            'response' => $response
        ]);
    }

    /**
     * @Route("/tickets/changeStatus/{id}", name="changeStatus")
     *
     */
    public function changeStatus($id): JsonResponse
    {
        $t = $this->em->getRepository(Ticket::class)->findOneBy([
            'id' => $id
        ]);
        $flag = false;
        $msg = "Hubo algun problema";
        if (isset($_POST['st']) && !empty($_POST['st'])) {
            if ($t != null) {
                $t->setStatusTicket($_POST['st']);
                $this->em->persist($t);
                try {
                    $this->em->flush();
                    $flag = true;
                    $msg = "Se ha modificado correctamente";
                } catch (\Exception $e) {
                    $msg = $e->getMessage();
                }
            }
        }
        return new JsonResponse([
            'status' => $flag,
            'msg' => $msg
        ]);
    }

    /**
     * @Route("/tickets/comment/{id}", name="newComment")
     *
     */
    public function comment($id, Request $request): JsonResponse
    {
        $flag = true;
        $msg = "";
        $html = "";
        $extension = "";
        $newFilename = "";
        if ($request->isXmlHttpRequest()) {
            if($request->get('c') != "" || $request->files->get('i') != null){
                    $t = $request->get('c');
                    $i = $request->files->get('i');
                    if($i !=  null){
                        $extension = pathinfo($i->getClientOriginalName(), PATHINFO_EXTENSION);
                        if($extension == "jpg" || $extension == "png" || $extension == "bat"){
                            $originalFilename = pathinfo($i->getClientOriginalName(), PATHINFO_FILENAME);
                            $newFilename = $originalFilename.'-'.uniqid().'.'.$extension;
                            $newFilename = str_replace(' ', '', $newFilename);
                            $i->move(
                                $this->getParameter('image'),
                                $newFilename
                            );
                        }else{
                            $flag = false;
                            $msg = "El tipo de archivo no es admitido, solo JPG, PNG o BAT";
                        }
                    }
                    if($flag){
                        $c = new Comentarios();
                        if($i !=  null){
                            if($extension == "jpg" || $extension == "png" ){
                                $c->setImageComment(true);
                            }
                            $c->setFilename("".$newFilename);
                        }
                        $c->setCommentComment("" . $t);
                        $c->setCreatedAtComment(new \DateTime());
                        $c->setFkTicket($this->em->getRepository(Ticket::class)->findOneBy([
                            'id' => $id
                        ]));
                        try {
                            $this->em->persist($c);
                            $this->em->flush();
                            $flag = true;

                            $html = $this->renderView('tickets/coments/comment.html.twig', [
                                'i' => $c->getId(),
                                'c' => $c->getCommentComment(),
                                'st' => $c->getImageComment(),
                                'file' => $c->getFilename(),
                            ]);
                        } catch (\Exception $e) {
                            $msg = $e->getMessage();
                        }
                    }
            }else{
                $flag = false;
                $msg = "Por favor no dejes los campos vacios";
            }
        } else {
            $flag = false;
            $msg = "Algo salio mal";

templates/tickets/clientSelector.html.twig
<div class= "overflow-hidden flex items-center justify-center" >
  <div class="overflow-hidden sm:rounded-md bg-white" style="margin-top:3px;margin-bottom:3px;padding:10px">
    <div class="inset-x-0 bottom-0">

      <table id="tabla-clientes" class="">
        <thead class="text-white">
        <tr style=" background-color:#1DABE0" class="block text-sm font-medium  bold flex flex-col flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
          <th class="p-3 text-left"></th>
          <th class="p-3 text-left"></th>
          <th class="p-3 text-left"></th>
          <th class="p-3 text-left"></th>
          <th class="p-3 text-left"></th>
        </tr>
        </thead>
      </table>
    </div>
  </div>
</div>
<script>
    $(document).ready(function() {
        let dataSet = "{{ response }}";
        let dataSetRemove = JSON.parse(dataSet.replace(/&quot;/g, '"'));
        let table = $('#tabla-clientes').DataTable({
            data: dataSetRemove,
            language: {
                'paginate': {
                    'previous': '<button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-r rounded-l">Prev</button>',
                    'next': '<button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-r rounded-l">Next</button>'
                },
                searchPlaceholder: "Buscar por nombre...",
            },
            "bLengthChange": false,
            "bFilter": true,
            "bInfo": false,
            "bAutoWidth": false,
            columns: [
                {title: "#", "width": 100},
                {title: "Nombre", "width": 300},
                {title: "Correo", "width": 100},
                {title: "Telefono", "width": 100},
                {title: "", "width": 200},
            ],
            "columnDefs": [{
                "targets": -1,
                "data": null,
                "width": 300,
                "defaultContent": "<button id='view' class='view bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>Crear ticket</button>"

            }]
        });
        table.on( 'click','button', function () {
            let action = this.id;
            let is = $(this);
            let row = table.row( is.parents('tr') );
            let data = row.data();
            if (action==='view'){
                window.location.href = "/tickets/create/"+data[0];
            }
        } );
        let input = $('#tabla-clientes_filter label input');
        $("#tabla-clientes_filter label").html('').append(input);
        $('#tabla-clientes_filter  label input').on( 'focus', function () {
            $(this).on("keyup", function() {
                let value = $(this).val().toLowerCase();
                table.columns(1).search(value).draw();
            });
        });
    });
</script>

templates/tickets/create.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <div class="overflow-hidden flex flex-shrink p-4 md:flex-shrink-0">
        <div style="width:1320px; margin:0 auto; ">
            <span style="font-size:38px;font-family: 'Gill Sans Extrabold', Helvetica, sans-serif">{{ name }}</span>
        </div>
    </div>
    <div class= "overflow-hidden flex items-center justify-center" >
        <div class="shadow overflow-hidden sm:rounded-md bg-white" style="margin-top:3px;margin-bottom:3px;padding:10px">
            <div class="inset-x-0 bottom-0">
                <div style="position:absolute;z-index:1">
                </div>
                <table id="tabla-clientes" class="">
                    <thead class="text-white">
                        <tr style=" background-color:#1DABE0" class="block text-sm font-medium  bold flex flex-col flex-no wrap sm:table-row rounded-l-lg sm:rounded-none mb-2 sm:mb-0">
                            <th class="p-3 text-left"></th>
                            <th class="p-3 text-left"></th>
                            <th class="p-3 text-left"></th>
                            <th class="p-3 text-left"></th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
  <script>
      let dataSet = "{{ response }}";
      let dataSetRemove = JSON.parse(dataSet.replace(/&quot;/g,'"'));
      let table = $('#tabla-clientes').DataTable( {
          data: dataSetRemove,
          "bLengthChange": false,
          "bFilter": true,
          "bInfo": false,
          "bAutoWidth": false ,
          language: {
              'paginate': {
                  'previous': '<button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-r rounded-l">Prev</button>',
                  'next':'<button class="bg-gray-300 hover:bg-gray-400 text-gray-800 font-bold py-2 px-4 rounded-r rounded-l">Next</button>'
              },
              searchPlaceholder: "Buscar...",
          },
          columns: [
              { title: "#", width: 100 },
              { title: "Direccion", width: 200 },
              { title: "IP", width: 300 },
              { title: "", width: 200},
          ],
          "columnDefs": [ {
              "targets": -1,
              "data": null,
              "defaultContent": "<button id='view' class='view bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded'>Generar ticket</button>"
          } ]
      } );
      $('#tabla-clientes tbody').on( 'click','button', function () {
          let action = this.id;
          let data = table.row( $(this).parents('tr') ).data();
          if (action==='view')
              window.location.href = "/tickets/create/"+"{{ id }}"+"/"+data[0];
      } );
     /* let m = $("#new_ticket_fkClient :selected");
      function startFetch(v){
          $.ajax({
              type: 'POST',
              url: '/tickets/fetchAddress/'+v,
              dataType: 'json',
              success: function(address){
                  $("#new_ticket_fkAddress").empty();
                  for (let i=0;i<address.address.length;i++){
                      $('<option/>').val(address.address[i]['id']).html(address.address[i]['address']).appendTo('#new_ticket_fkAddress');
                  }

              }
          });
      }
      startFetch(m.val());
      $("#new_ticket_fkClient").on('change', function(){
          let sel = this;
          startFetch(sel.value);
      })

      $("#form-ticket").submit(function(e){
          e.preventDefault();
          let form = new FormData(this);
          alert(form.get('new_ticket[fkAddress]'));
          $.ajax({
              type: 'POST',

              processData: false,
              contentType: false,
              data: form,
              dataType: 'json',
              success: function(s){
                  $.sweetModal({
                      content: s.msg,
                      icon: $.sweetModal.ICON_ERROR,
                  });
                  /*if(s.status == true){
                      $.sweetModal({
                          content: s.msg,
                          icon: $.sweetModal.ICON_SUCCESS,
                          onClose: function(){
                              window.location.href='/clientes'
                          }
                      });
                  }else{
                      $.sweetModal({
                          content: s.msg,
                          icon: $.sweetModal.ICON_ERROR,

                      });
                  }*/
            /* }
          });

      })*/
  </script>

{% endblock %}

templates/tickets/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}
  <div id="app" class="sm:mt-0 px-6">
    <div class="md:grid md:grid-cols-6 md:gap-6 md:grid-rows-1 md:mt-5">
      <div class="md:mt-0 md:col-start-1 col-end-4">
        <p class="block uppercase tracking-wide text-gray-700 text-s font-bold mb-2" style="">Informacion del ticket</p>
        <div class="shadow overflow-hidden sm:rounded-md">
          <div class="px-4 py-5 bg-white sm:p-6">
            <div class="grid grid-cols-6 gap-6">
              <div class="col-span-2">
                <label for="nombre" class="block text-sm font-medium text-gray-700 bold">Cliente:</label>
                <p class="font-bold">{{ ticket.getFkClient.getNameClient }}</p>
              </div>
              <div class="col-span-1">
                <label for="email" class="block text-sm font-medium text-gray-700 bold">No.ticket:</label>
                <p class="font-bold">{{ ticket.getId }}</p>
              </div>
              <div class="col-span-3">
                <label for="domicilio" class="block text-sm font-medium text-gray-700 bold">Tipo de Problema:</label>
                <p class="font-bold">{{ ticket.typeTicket }}</p>
              </div>
              <div class="col-span-6">
                <label for="telefono" class="block text-sm font-medium text-gray-700 bold">Descripcion:</label>
                <p class="font-bold">{{ ticket.getDescTicket }}</p>
              </div>
              <div class="col-span-6">
                <label for="telefono" class="block text-sm font-medium text-gray-700 bold">Direccion:</label>
                <p class="font-bold">{{ ticket.getService.getFkAddress.getNameAddress}}</p>
              </div>
              <div class="col-span-6">
                <label for="sitios" class="block text-sm font-medium text-gray-700 bold">Estado del ticket</label>
                <select id="estado" name="estado" autocomplete="country" class="mt-1 block w-full py-2 px-3 border border-gray-300 bg-white rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm">
                  <option value="Abierto" {% if ticket.getStatusTicket == "Abierto" %}selected{% endif%} >Abierto</option>
                  <option value="Nuevo" {% if ticket.getStatusTicket == "Nuevo" %}selected{% endif%}>Nuevo</option>
                  <option value="Resuelto" {% if ticket.getStatusTicket == "Resuelto" %}selected{% endif%}>Resuelto</option>
                </select>
              </div>
              <div class="col-span-6 sm:col-span-3">
                <label for="paquete" class="block text-sm font-medium text-gray-700 bold">Fecha Registrada</label>
                <p class="font-bold">{{ ticket.getDateTicket|date('Y-m-d')  }}</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="md:col-start-4 md:col-end-7">
        <p class="block uppercase tracking-wide text-gray-700 text-s font-bold mb-2" style="">Comentarios</p>
        <div class="grid bg-white shadow overflow-hidden sm:rounded-md gap-6 mb-8 p-5" >
          <div class="min-w-0 dark:bg-gray-800 md:overflow-y-auto md:h-72 " id="comentarios" style="height: 400px; padding-right: 10px;">
            {% if ticket.getComentarios|length == 0 %}
              No hay comentarios
            {% else %}
              {% for c in response %}
                {{ c.comment|markdown_to_html }}
              {% endfor %}
            {% endif %}
          </div>
          <div>
            <form  id="registrar" class="registrar">
              <div>
              <textarea type="text" id="comentario" name="c" class="min-w-full resize-none p-6 rounded-lg bg-gray-200" placeholder="Agregar comentario..."></textarea>
              </div>
              <div class="custom-file">
                <input type="file" name="i" class="custom-file-input" id="chooseFile">
                <button id="comentar" type="submit" class="inline-flex justify-center py-2 px-4 border border-transparent shadow-sm text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                  Comentar
                </button>
              </div>

            </form>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script>
      $( document ).ready(function() {
          document.getElementById("estado").onchange = function(e){
              $.sweetModal.confirm('¿Seguro de cambiar el estado?', function() {
                  $.ajax({
                      type: "POST",
                      url: '{{ path('changeStatus', {id: ticket.getId}) }}',
                      data: {
                          st :$("#estado").val()
                      },
                      dataType: 'json',
                      success: function(s){
                          if(s.status === true){
                              $.sweetModal(s.msg);
                          }

                      }
                  })
              }, function() {
                  let newOptions = {
                      "Abierto" : "Abierto",
                      "Nuevo" : "Nuevo",
                      "Resuelto" : "Resuelto"
                  };
                  let $el = $("#estado");
                  $el.empty();
                  $.each(newOptions, function(key,value) {
                      if(value === "{{ ticket.getStatusTicket }}"){
                          $el.append($("<option></option>").attr({
                              "value": value,
                              "selected": "selected"
                          }).text(key));
                      }else{
                          $el.append($("<option></option>").attr("value", value).text(key));
                      }
                  });
              });
          }
        $( "#registrar" ).submit(function( event ) {
            event.preventDefault();
            $.ajax({
              type: 'POST',
              url: "{{ path('newComment', { id: ticket.getId }) }}",
              processData: false,
              contentType: false,
              data: new FormData(this),
              dataType: 'json',
              success: function(response) {
                if(response.status === true){
                  $("#comentarios").append(response.html);
                  $("#comentario").val("");
                  $("#chooseFile").val("");

                }else{
                  $.sweetModal(response.msg);
                }
              },
            });
          })
      });

      function deleteComment(id){
        $.sweetModal.confirm('¿Seguro de eliminar este comentario?', function() {
          $.ajax({
            type: "POST",
            url: '/tickets/deletecomment/'+id,
            dataType: 'json',
            success: function(s){
              if(s.status === true){
                $("#comment"+id).remove();
                $.sweetModal(s.msg);
              }
            }
          })
        }, function() {

        })
      }
  </script>
{% endblock %}